INSERT INTO series (title, author_id, subgenre_id) VALUES ("Monkeys Paw", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Crocodile King", 2, 2);
INSERT INTO subgenres (name) VALUES ("Goat Fantasy");
INSERT INTO subgenres (name) VALUES ("TV Cooking Fantasy");
INSERT INTO authors (name) VALUES ("Bud Powell");
INSERT INTO authors (name) VALUES ("Art Blakey");
INSERT INTO books (title, year, series_id) VALUES ("Space Chimps", 1987, 1);
INSERT INTO books (title, year, series_id) VALUES ("Rockets and Jungles", 1989, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Banana We Left Behind", 1991, 1);
INSERT INTO books (title, year, series_id) VALUES ("Cooking on the Vilio River", 1987, 2);
INSERT INTO books (title, year, series_id) VALUES ("Chopped up and Stewed", 1988, 2);
INSERT INTO books (title, year, series_id) VALUES ("Titanium Chefs of Snoz", 1990, 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Grug", "To space or the boggle tree", "Maldorf monkey", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Gruff", "I like to eat not travel", "Maldorf monkey", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Billsy", "Its a pirating life for me", "slug", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Jeff", "Go big", "slug", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Amanda", "I love roses in everything", "Shelfish Hippo", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Berand", "Never use a chicken breast when you could use safish thigh", "bilge whale", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Bilbo", "I've forgotten my pipe", "hobbit", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Jessup", "I love parsnips", "jasper croc", 2);
INSERT INTO character_books  (book_id, character_id) VALUES (1, 1);
INSERT INTO character_books  (book_id, character_id) VALUES (2, 1);
INSERT INTO character_books  (book_id, character_id) VALUES (3, 1);
INSERT INTO character_books  (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books  (book_id, character_id) VALUES (2, 2);
INSERT INTO character_books  (book_id, character_id) VALUES (3, 2);
INSERT INTO character_books  (book_id, character_id) VALUES (1, 3);
INSERT INTO character_books  (book_id, character_id) VALUES (1, 4);
INSERT INTO character_books  (book_id, character_id) VALUES (4, 5);
INSERT INTO character_books  (book_id, character_id) VALUES (5, 5);
INSERT INTO character_books  (book_id, character_id) VALUES (6, 5);
INSERT INTO character_books  (book_id, character_id) VALUES (4, 6);
INSERT INTO character_books  (book_id, character_id) VALUES (5, 6);
INSERT INTO character_books  (book_id, character_id) VALUES (6, 6);
INSERT INTO character_books  (book_id, character_id) VALUES (4, 7);
INSERT INTO character_books  (book_id, character_id) VALUES (4, 8);